#!/bin/bash

# Auto-Build Environment Setup for Portal APK UI Enhancement
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Android Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check if ADB is installed
if ! command -v adb &> /dev/null; then
    echo -e "${RED}Error: ADB not found. Please install Android SDK Platform Tools.${NC}"
    exit 1
fi

# Check if Gradle wrapper exists
if [ ! -f "droidrun-controller/portal-apk/gradlew" ]; then
    echo -e "${RED}Error: Gradle wrapper not found in droidrun-controller/portal-apk/${NC}"
    exit 1
fi

echo -e "${GREEN}Prerequisites check passed${NC}"

# ============================================
# BUILD APK
# ============================================

echo ""
echo "Building APK..."
cd droidrun-controller/portal-apk

# Make gradlew executable
chmod +x ./gradlew

# Build debug APK
./gradlew assembleDebug

if [ $? -eq 0 ]; then
    echo -e "${GREEN}APK build successful${NC}"
else
    echo -e "${RED}APK build failed${NC}"
    exit 1
fi

# ============================================
# DEVICE CONNECTION
# ============================================

echo ""
echo "Checking for connected devices..."
adb devices -l

DEVICE_COUNT=$(adb devices | grep -v "List" | grep "device" | wc -l)

if [ $DEVICE_COUNT -eq 0 ]; then
    echo -e "${YELLOW}Warning: No Android devices connected${NC}"
    echo "Please connect a device or start an emulator to install the APK"
    echo ""
    echo "APK location: droidrun-controller/portal-apk/app/build/outputs/apk/debug/app-debug.apk"
    echo ""
    echo "Manual installation:"
    echo "  adb install -r app/build/outputs/apk/debug/app-debug.apk"
    exit 0
fi

# ============================================
# INSTALL APK
# ============================================

echo ""
echo "Installing APK on device..."
adb install -r app/build/outputs/apk/debug/app-debug.apk

if [ $? -eq 0 ]; then
    echo -e "${GREEN}APK installed successfully${NC}"
else
    echo -e "${RED}APK installation failed${NC}"
    exit 1
fi

# ============================================
# LAUNCH APP
# ============================================

echo ""
echo "Launching Agent Portal..."
adb shell am start -n com.agent.portal/.MainActivity

if [ $? -eq 0 ]; then
    echo -e "${GREEN}App launched successfully${NC}"
else
    echo -e "${YELLOW}Warning: Could not launch app automatically${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Portal APK Development Environment:"
echo "  Project:     droidrun-controller/portal-apk"
echo "  Package:     com.agent.portal"
echo "  Min SDK:     26 (Android 8.0)"
echo "  Target SDK:  34 (Android 14)"
echo ""
echo "Useful commands:"
echo "  Build:       cd droidrun-controller/portal-apk && ./gradlew assembleDebug"
echo "  Install:     adb install -r app/build/outputs/apk/debug/app-debug.apk"
echo "  Launch:      adb shell am start -n com.agent.portal/.MainActivity"
echo "  Logs:        adb logcat -s AgentPortal"
echo "  Devices:     adb devices"
echo ""
echo "To enable debugging features:"
echo "  Accessibility: Settings > Accessibility > Agent Portal"
echo "  Overlay:       Settings > Apps > Special access > Display over other apps"
echo "  Keyboard:      Settings > System > Languages & input > Virtual keyboard"
echo ""
